config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'
  get '/show', to: 'pages#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter] #今回はTwitterを指定


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<header>
  <nav>
    <% if user_signed_in? %>
      <strong><%= link_to current_user.username page_show_path %></strong>
      <%= link_to 'プロフィール編集', edit_user_registration %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: 'delete' %>
    <% else %>
      <%= link_to 'サインアップ', new_user_session_path %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseRails5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome !</h1>
<p>this is test devise of rails gem</p>
<% if user_signed_in? %>
<%= link_to 'プロフィール', show_path %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to 'サインアップ', new_user_registration_path %>
<%= link_to 'ログイン', new_user_session_path %>
<% end %>

app/views/pages/show.html.erb
<h1>Hello, <%= current_user.username %> !!</h1>
<p>this is user pages</p>